version: '3.9'

services:
  db:
    image: postgres:14.1
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}